// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// findMS
List findMS(std::string fileloc, NumericVector minrepeats, NumericVector tolerancefactors);
RcppExport SEXP _micRocounter_findMS(SEXP filelocSEXP, SEXP minrepeatsSEXP, SEXP tolerancefactorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fileloc(filelocSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type minrepeats(minrepeatsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tolerancefactors(tolerancefactorsSEXP);
    rcpp_result_gen = Rcpp::wrap(findMS(fileloc, minrepeats, tolerancefactors));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_micRocounter_findMS", (DL_FUNC) &_micRocounter_findMS, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_micRocounter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
